// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  var bodyParser, express, morgan;

  express = require('express', bodyParser = require('body-parser', morgan = require('morgan')));

  this.ExpressApp = (function() {

    function ExpressApp() {
      this.app = express();
    }

    ExpressApp.prototype.init = function(bayeux, usersManager, pushService) {
      var _this = this;
      this.app.use(morgan());
      this.app.use(bodyParser());
      this.app.use(express["static"](__dirname + '/public'));
      this.app.get('/', function(req, res) {
        return res.send('Pictie socket server is on /bayeux ; faye client is on bayeux/client.js');
      });
      this.app.get('/users', function(req, res) {
        return res.json(usersManager.allUsers());
      });
      this.app.all('/messages', function(req, res, next) {
        res.header("Access-Control-Allow-Origin", "*");
        res.header("Access-Control-Allow-Headers", "X-Requested-With, Content-Type");
        return next();
      });
      this.app.options('/messages', function(req, res) {
        return res.end();
      });
      this.app.post('/messages', function(req, res) {
        var message;
        message = {
          sender: req.body.sender,
          recipient: req.body.recipient,
          body: req.body.body
        };
        bayeux.getClient().publish("/user/" + req.body.recipient, {
          evt: 'message',
          message: message
        });
        return res.json(message);
      });
      this.app.post('/push_registration', function(req, res) {
        console.log("received post on /push_registration " + (JSON.stringify(req.body)));
        usersManager.storePushInfo(req.body.userId, req.body.pushProvider, req.body.pushToken);
        return res.json({
          'result': 'success'
        });
      });
      this.app.post('/push_test', function(req, res) {
        console.log("received post on /push_test with " + (JSON.stringify(req.body)));
        pushService.sendNotification(req.body.userId, req.body.message);
        return res.json({
          'result': 'success'
        });
      });
      return this.app.use(function(req, res, next) {
        return res.send(404, 'Sorry cant find that!');
      });
    };

    return ExpressApp;

  })();

}).call(this);
