// Generated by CoffeeScript 1.3.3
(function() {
  var _env, _fs, _url;

  _fs = require('fs');

  _url = require('url');

  _env = require('node-env-file');

  if (_fs.existsSync('.env')) {
    _env('.env');
  }

  exports.redis_url = function() {
    return _url.parse(process.env.REDISTOGO_URL);
  };

  exports.port = function(http_port) {
    return parseInt(process.env.PORT) || http_port || 5000;
  };

  exports.env = {
    prod: process.env.ENV === 'prod',
    dev: process.env.ENV !== 'prod'
  };

}).call(this);
