// Generated by CoffeeScript 1.3.3
(function() {
  var url;

  url = require('url');

  exports.redis_url = function() {
    return url.parse(process.env.REDISTOGO_URL || 'redis://localhost:6379');
  };

  exports.port = function(http_port) {
    return parseInt(process.env.PORT) || http_port || 5000;
  };

  exports.env = {
    prod: process.env.ENV === 'prod',
    dev: process.env.ENV !== 'prod'
  };

}).call(this);
