// Generated by CoffeeScript 1.3.3
(function() {
  var _config, _server;

  _config = require('./config', _server = require('./server'));

  exports.start = function(http_port) {
    var server;
    server = new _server.Server(_config);
    return server.start(http_port, function() {});
  };

  this.start();

}).call(this);
