// Generated by CoffeeScript 1.3.3
(function() {
  var _env, _server;

  _server = require('./server');

  _env = require('node-env-file');

  _env('.env');

  exports.start = function(http_port) {
    var server;
    server = new _server.Server;
    return server.start(http_port, function() {});
  };

  this.start();

}).call(this);
