// Generated by CoffeeScript 1.3.3
(function() {
  var crypto;

  crypto = require('crypto');

  exports.encrypt_token = function(token) {
    return crypto.createHash('sha1').update(token).digest('hex');
  };

}).call(this);
